#ifndef MICROTRACY_H
#define MICROTRACY_H

#include "queue.h"
#include "lz4.h"

#define UTRACY_PROTOCOL_VERSION (56)

#define UTRACY_HANDSHAKE_SHIBBOLETH_SIZE (8)
#define UTRACY_HANDSHAKE_SHIBBOLETH ("TracyPrf")

#define UTRACY_HANDSHAKE_PENDING (0)
#define UTRACY_HANDSHAKE_WELCOME (1)
#define UTRACY_HANDSHAKE_PROTOCOL_MISMATCH (2)
#define UTRACY_HANDSHAKE_NOT_AVAILABLE (3)
#define UTRACY_HANDSHAKE_DROPPED (4)

#define UTRACY_WELCOMEMSG_PROGRAM_NAME_SIZE (64)
#define UTRACY_WELCOMEMSG_HOST_INFO_SIZE (1024)

#ifdef _MSC_VER
#	pragma pack(push, 1)
#endif

struct utracy_welcomemsg {
	double timerMul;
	long long initBegin;
	long long initEnd;
	long long delay;
	long long resolution;
	long long epoch;
	long long exectime;
	long long pid;
	long long samplingPeriod;
	char unsigned flags;
	char unsigned cpuArch;
	char cpuManufacturer[12];
	int unsigned cpuId;
	char programName[UTRACY_WELCOMEMSG_PROGRAM_NAME_SIZE];
	char hostInfo[UTRACY_WELCOMEMSG_HOST_INFO_SIZE];
}
#ifndef _MSC_VER
__attribute__((packed))
#endif
;

struct utracy_recv_query_packet {
	char unsigned type;
	long long unsigned ptr;
	int unsigned extra;
}
#ifndef _MSC_VER
__attribute__((packed))
#endif
;

#ifdef _MSC_VER
#	pragma pack(pop)
#endif

#define UTRACY_QUEUE_TYPE_ZONETEXT (0)
#define UTRACY_QUEUE_TYPE_ZONENAME (1)
#define UTRACY_QUEUE_TYPE_MESSAGE (2)
#define UTRACY_QUEUE_TYPE_MESSAGECOLOR (3)
#define UTRACY_QUEUE_TYPE_MESSAGECALLSTACK (4)
#define UTRACY_QUEUE_TYPE_MESSAGECOLORCALLSTACK (5)
#define UTRACY_QUEUE_TYPE_MESSAGEAPPINFO (6)
#define UTRACY_QUEUE_TYPE_ZONEBEGINALLOCSRCLOC (7)
#define UTRACY_QUEUE_TYPE_ZONEBEGINALLOCSRCLOCCALLSTACK (8)
#define UTRACY_QUEUE_TYPE_CALLSTACKSERIAL (9)
#define UTRACY_QUEUE_TYPE_CALLSTACK (10)
#define UTRACY_QUEUE_TYPE_CALLSTACKALLOC (11)
#define UTRACY_QUEUE_TYPE_CALLSTACKSAMPLE (12)
#define UTRACY_QUEUE_TYPE_CALLSTACKSAMPLECONTEXTSWITCH (13)
#define UTRACY_QUEUE_TYPE_FRAMEIMAGE (14)
#define UTRACY_QUEUE_TYPE_ZONEBEGIN (15)
#define UTRACY_QUEUE_TYPE_ZONEBEGINCALLSTACK (16)
#define UTRACY_QUEUE_TYPE_ZONEEND (17)
#define UTRACY_QUEUE_TYPE_LOCKWAIT (18)
#define UTRACY_QUEUE_TYPE_LOCKOBTAIN (19)
#define UTRACY_QUEUE_TYPE_LOCKRELEASE (20)
#define UTRACY_QUEUE_TYPE_LOCKSHAREDWAIT (21)
#define UTRACY_QUEUE_TYPE_LOCKSHAREDOBTAIN (22)
#define UTRACY_QUEUE_TYPE_LOCKSHAREDRELEASE (23)
#define UTRACY_QUEUE_TYPE_LOCKNAME (24)
#define UTRACY_QUEUE_TYPE_MEMALLOC (25)
#define UTRACY_QUEUE_TYPE_MEMALLOCNAMED (26)
#define UTRACY_QUEUE_TYPE_MEMFREE (27)
#define UTRACY_QUEUE_TYPE_MEMFREENAMED (28)
#define UTRACY_QUEUE_TYPE_MEMALLOCCALLSTACK (29)
#define UTRACY_QUEUE_TYPE_MEMALLOCCALLSTACKNAMED (30)
#define UTRACY_QUEUE_TYPE_MEMFREECALLSTACK (31)
#define UTRACY_QUEUE_TYPE_MEMFREECALLSTACKNAMED (32)
#define UTRACY_QUEUE_TYPE_GPUZONEBEGIN (33)
#define UTRACY_QUEUE_TYPE_GPUZONEBEGINCALLSTACK (34)
#define UTRACY_QUEUE_TYPE_GPUZONEBEGINALLOCSRCLOC (35)
#define UTRACY_QUEUE_TYPE_GPUZONEBEGINALLOCSRCLOCCALLSTACK (36)
#define UTRACY_QUEUE_TYPE_GPUZONEEND (37)
#define UTRACY_QUEUE_TYPE_GPUZONEBEGINSERIAL (38)
#define UTRACY_QUEUE_TYPE_GPUZONEBEGINCALLSTACKSERIAL (39)
#define UTRACY_QUEUE_TYPE_GPUZONEBEGINALLOCSRCLOCSERIAL (40)
#define UTRACY_QUEUE_TYPE_GPUZONEBEGINALLOCSRCLOCCALLSTACKSERIAL (41)
#define UTRACY_QUEUE_TYPE_GPUZONEENDSERIAL (42)
#define UTRACY_QUEUE_TYPE_PLOTDATA (43)
#define UTRACY_QUEUE_TYPE_CONTEXTSWITCH (44)
#define UTRACY_QUEUE_TYPE_THREADWAKEUP (45)
#define UTRACY_QUEUE_TYPE_GPUTIME (46)
#define UTRACY_QUEUE_TYPE_GPUCONTEXTNAME (47)
#define UTRACY_QUEUE_TYPE_CALLSTACKFRAMESIZE (48)
#define UTRACY_QUEUE_TYPE_SYMBOLINFORMATION (49)
#define UTRACY_QUEUE_TYPE_CODEINFORMATION (50)
#define UTRACY_QUEUE_TYPE_EXTERNALNAMEMETADATA (51)
#define UTRACY_QUEUE_TYPE_SYMBOLCODEMETADATA (52)
#define UTRACY_QUEUE_TYPE_FIBERENTER (53)
#define UTRACY_QUEUE_TYPE_FIBERLEAVE (54)
#define UTRACY_QUEUE_TYPE_TERMINATE (55)
#define UTRACY_QUEUE_TYPE_KEEPALIVE (56)
#define UTRACY_QUEUE_TYPE_THREADCONTEXT (57)
#define UTRACY_QUEUE_TYPE_GPUCALIBRATION (58)
#define UTRACY_QUEUE_TYPE_CRASH (59)
#define UTRACY_QUEUE_TYPE_CRASHREPORT (60)
#define UTRACY_QUEUE_TYPE_ZONEVALIDATION (61)
#define UTRACY_QUEUE_TYPE_ZONECOLOR (62)
#define UTRACY_QUEUE_TYPE_ZONEVALUE (63)
#define UTRACY_QUEUE_TYPE_FRAMEMARKMSG (64)
#define UTRACY_QUEUE_TYPE_FRAMEMARKMSGSTART (65)
#define UTRACY_QUEUE_TYPE_FRAMEMARKMSGEND (66)
#define UTRACY_QUEUE_TYPE_SOURCELOCATION (67)
#define UTRACY_QUEUE_TYPE_LOCKANNOUNCE (68)
#define UTRACY_QUEUE_TYPE_LOCKTERMINATE (69)
#define UTRACY_QUEUE_TYPE_LOCKMARK (70)
#define UTRACY_QUEUE_TYPE_MESSAGELITERAL (71)
#define UTRACY_QUEUE_TYPE_MESSAGELITERALCOLOR (72)
#define UTRACY_QUEUE_TYPE_MESSAGELITERALCALLSTACK (73)
#define UTRACY_QUEUE_TYPE_MESSAGELITERALCOLORCALLSTACK (74)
#define UTRACY_QUEUE_TYPE_GPUNEWCONTEXT (75)
#define UTRACY_QUEUE_TYPE_CALLSTACKFRAME (76)
#define UTRACY_QUEUE_TYPE_SYSTIMEREPORT (77)
#define UTRACY_QUEUE_TYPE_TIDTOPID (78)
#define UTRACY_QUEUE_TYPE_HWSAMPLECPUCYCLE (79)
#define UTRACY_QUEUE_TYPE_HWSAMPLEINSTRUCTIONRETIRED (80)
#define UTRACY_QUEUE_TYPE_HWSAMPLECACHEREFERENCE (81)
#define UTRACY_QUEUE_TYPE_HWSAMPLECACHEMISS (82)
#define UTRACY_QUEUE_TYPE_HWSAMPLEBRANCHRETIRED (83)
#define UTRACY_QUEUE_TYPE_HWSAMPLEBRANCHMISS (84)
#define UTRACY_QUEUE_TYPE_PLOTCONFIG (85)
#define UTRACY_QUEUE_TYPE_PARAMSETUP (86)
#define UTRACY_QUEUE_TYPE_ACKSERVERQUERYNOOP (87)
#define UTRACY_QUEUE_TYPE_ACKSOURCECODENOTAVAILABLE (88)
#define UTRACY_QUEUE_TYPE_ACKSYMBOLCODENOTAVAILABLE (89)
#define UTRACY_QUEUE_TYPE_CPUTOPOLOGY (90)
#define UTRACY_QUEUE_TYPE_SINGLESTRINGDATA (91)
#define UTRACY_QUEUE_TYPE_SECONDSTRINGDATA (92)
#define UTRACY_QUEUE_TYPE_MEMNAMEPAYLOAD (93)
#define UTRACY_QUEUE_TYPE_STRINGDATA (94)
#define UTRACY_QUEUE_TYPE_THREADNAME (95)
#define UTRACY_QUEUE_TYPE_PLOTNAME (96)
#define UTRACY_QUEUE_TYPE_SOURCELOCATIONPAYLOAD (97)
#define UTRACY_QUEUE_TYPE_CALLSTACKPAYLOAD (98)
#define UTRACY_QUEUE_TYPE_CALLSTACKALLOCPAYLOAD (99)
#define UTRACY_QUEUE_TYPE_FRAMENAME (100)
#define UTRACY_QUEUE_TYPE_FRAMEIMAGEDATA (101)
#define UTRACY_QUEUE_TYPE_EXTERNALNAME (102)
#define UTRACY_QUEUE_TYPE_EXTERNALTHREADNAME (103)
#define UTRACY_QUEUE_TYPE_SYMBOLCODE (104)
#define UTRACY_QUEUE_TYPE_SOURCECODE (105)
#define UTRACY_QUEUE_TYPE_FIBERNAME (106)

#define UTRACY_RECV_QUERY_TERMINATE (0)
#define UTRACY_RECV_QUERY_STRING (1)
#define UTRACY_RECV_QUERY_THREADSTRING (2)
#define UTRACY_RECV_QUERY_SOURCELOCATION (3)
#define UTRACY_RECV_QUERY_PLOTNAME (4)
#define UTRACY_RECV_QUERY_FRAMENAME (5)
#define UTRACY_RECV_QUERY_PARAMETER (6)
#define UTRACY_RECV_QUERY_FIBERNAME (7)
#define UTRACY_RECV_QUERY_DISCONNECT (8)
#define UTRACY_RECV_QUERY_CALLSTACKFRAME (9)
#define UTRACY_RECV_QUERY_EXTERNALNAME (10)
#define UTRACY_RECV_QUERY_SYMBOL (11)
#define UTRACY_RECV_QUERY_SYMBOLCODE (12)
#define UTRACY_RECV_QUERY_CODELOCATION (13)
#define UTRACY_RECV_QUERY_SOURCECODE (14)
#define UTRACY_RECV_QUERY_DATATRANSFER (15)
#define UTRACY_RECV_QUERY_DATATRANSFERPART (16)

DWORD WINAPI utracy_thread_start(PVOID user);

struct utracy {
	struct {
		long long init_begin;
		long long init_end;
		double multiplier;
		long long resolution;
		long long delay;
		long long epoch;
		long long exectime;
		DWORD last_heartbeat;
	} info;

	struct {
		WSADATA wsadata;
		SOCKET server;
		SOCKET client;
	} sock;

	/* 16KB + 4 bytes for the default LZ4_MEMORY_USAGE 14 */
	LZ4_stream_t stream;

	int unsigned buf_len;
	char *frame_buf;
	/* lz4 compressed buffer */
	char *buf;

	int unsigned raw_buf_len;
	int unsigned raw_buf_head;
	int unsigned raw_buf_tail;
	char *raw_buf;

	struct event_queue event_queue;
	int unsigned current_tid;
	long long thread_time;
};

extern struct utracy utracy;
extern int utracy_dequeue_event(struct event *evt);
extern int utracy_commit(void);

/* profiled program api */
struct utracy_source_location {
	char const *name;
	char const *function;
	char const *file;
	int unsigned line;
	int unsigned color;
};

void utracy_emit_zone_begin(struct utracy_source_location const *const srcloc);
void utracy_emit_zone_end(void);
void utracy_emit_zone_color(int unsigned color);
void utracy_emit_frame_mark(char const *const name);
void utracy_emit_plot(char const *const name, float value);
void utracy_emit_thread_name(char const *const name);

#endif
