name: Build & Publish

on:
  pull_request:
    branches: [master]
  push:

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      # Install Deps
      - uses: lukka/get-cmake@latest

      # MSVC
      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: Win32

      - name: Build w/ MSVC
        run: ninja -f build\msvc.ninja

      # LLVM
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: |
            C:/Program Files/LLVM
            ./llvm
          key: llvm-14

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "14"
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}

      - name: Build w/ LLVM
        run: ninja -f build\llvm.ninja

      # GCC
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: i686

      - name: Build w/ GCC
        run: ninja -f build\gcc.ninja

      # Upload
      - uses: actions/upload-artifact@v3
        with:
          name: Output Artifacts
          path: |
            bin/msvc/prof.dll
            bin/llvm/prof.dll
            bin/gcc/prof.dll
            LICENSE-lz4.txt
            LICENSE-minhook.txt
